---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gojo satoru.
--- DateTime: 2025/9/19 上午9:41
---

-- 锁的key
local key = KEYS[1]

--当前线程标识
local thread = ARGV[1]

--获取锁中的线程标识 get key
local id = redis.call('get',key)

--比较线程标识与锁中的标识是否一致
if(id==threadId)then
    --释放锁 del key
    return redis.call('del',key)
end
return 0